
[default]
DEBUG = false
FLASK_ADMIN_NAME = "Backend Admin"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
TITLE = "Backend"
SECRET_KEY = "jadkfbsdkjbfbh"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']



[development]
SQLALCHEMY_TRACK_MODIFICATIONS=false
TEMPLATES_AUTO_RELOAD = true
DEBUG = true

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'
